config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'

  get 'profiles/show'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'registrations#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :clothes
    resources :comments
    member do
      get 'like'
    end
  end
  
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  
  post 'profiles/search', as: 'search_users'
  
  get 'browse', to: 'posts#browse', as: :browse_posts
  
  # Route Existente
  get ':user_name', to: 'profiles#show', as: :profile
  # Nova Route
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  # Route actualizada
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]
  
  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
  
  def edit
  end
  
  def update
    if @user.update(profile_params)
      flash[:success] = 'O teu perfil foi atualizado.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
  
  def search
    @query = params[:query]
    @user = User.where("user_name LIKE ?", @query)
    if @user.blank?
      flash[:error] = 'Não existe nenhum utilizador com o nome ' + @query
      redirect_to :back
    else
      @user = @user.map{|u| u.user_name}
      redirect_to profile_path(@user)
    end
  end
  
  private
  
  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end
  
  def owned_profile
    unless current_user == @user
      flash[:alert] = "Este não é o teu perfil."
      redirect_to root_path
    end
  end
  
  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
    def current_user_is_following(current_user_id, followed_user_id)
        relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
        return true if relationship
    end
end

app/views/profiles/edit.html.haml
.posts-wrapper
    .post
        .post-body
            .image-wrap
                = form_for @user, url: {action: "update"}, html: {multipart: true } do |f|
                    .row
                        .col-md-12
                            .form-group.text-center
                                %h4 Alterar imagem de perfil
                                .img-circle
                                    = profile_avatar_select(@user)
                            .btngroup.text-center
                                = f.file_field :avatar, onChange: 'loadFile(event)'
                    .row
                        .col-md-12
                            .form-group.text-center
                                %h4 Atualizar descrição
                            .formtext.text-center
                                = f.text_area :bio, label: false, rows: 4, cols: 70
                    .btngroup.text-center
                        = f.submit "Atualizar", class: 'btn btn-success'

app/views/profiles/show.html.haml
.posts-wrapper
    .row.profile-header
        .col-md-5
            .img-circle
                = profile_avatar_select(@user)
        .col-md-7
            .user-name-and-follow
                %h3.profile-user-name
                    = @user.user_name
                %span
                    - if @user == current_user
                        = link_to 'Editar Perfil', edit_profile_path(@user.user_name), class: 'btn edit-button btn-sm'
                    - else
                        - if current_user_is_following(current_user.id, @user.id)
                            = link_to 'A Seguir', unfollow_user_path, remote: true, class: 'btn unfollow-button btn-sm', id: 'unfollow-button', method: :post
                        - else
                            = link_to 'Segue', follow_user_path, remote: true, class: 'btn follow-button btn-sm', id: 'follow-button', method: :post
            %p.profile-bio
                = @user.bio
            .user-statistics{:style => "margin-top:20px;"}
                %p
                    %b=pluralize(@user.posts.count,'Publicação','Publicações')
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    %b=pluralize(@user.followers.count,'Seguidor','Seguidores')
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp  
                    %b=pluralize(@user.following.count,'A Seguir','A Seguir')
    
-@posts.each do |post|
    = render 'posts/post', post: post