config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'

  get 'profiles/show'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'registrations#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :clothes
    resources :comments
    member do
      get 'like'
    end
  end
  
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  
  post 'profiles/search', as: 'search_users'
  
  get 'browse', to: 'posts#browse', as: :browse_posts
  
  # Route Existente
  get ':user_name', to: 'profiles#show', as: :profile
  # Nova Route
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  # Route actualizada
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :content, length: { minimum: 2, maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    
    def create
        @comment = @post.comments.new(comment_params)
        @comment.user_id = current_user.id
        
        if @comment.save
            respond_to do |format|
                format.html { redirect_to root_path}
                format.js
            end
        else
            flash[:alert] = "Alguma coisa correu mal com o teu comentário, tenta novamente."
            render root_path
        end
    end
    
    def destroy
        @comment = @post.comments.find(params[:id])

        if @comment.user_id == current_user.id || @post.user.id == current_user.id
            @comment.destroy
            respond_to do |format|
                format.html {redirect_to root_path}
                format.js
            end
        end
    end
    
    private 
    
    def comment_params
        params.require(:comment).permit(:content)
    end
    
    def find_post
        @post = Post.find(params[:post_id])
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
#comment
    .user-name
        = link_to comment.user.user_name, profile_path(comment.user.user_name)
    .comment-content
        = comment.content
    - if user_signed_in?
        - if comment.user == current_user || post.user.id == current_user.id
            = link_to post_comment_path(post,comment),title: "Eliminar Comentário", method: :delete, data: {}, remote: true do 
                %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%=j render @post.comments, post: @post, comment: @comment %>");