config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'

  get 'profiles/show'
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'registrations#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :clothes
    resources :comments
    member do
      get 'like'
    end
  end
  
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  
  post 'profiles/search', as: 'search_users'
  
  get 'browse', to: 'posts#browse', as: :browse_posts
  
  # Route Existente
  get ':user_name', to: 'profiles#show', as: :profile
  # Nova Route
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  # Route actualizada
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/post.rb
class Post < ActiveRecord::Base
    acts_as_votable
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :clothes, dependent: :destroy
    
    #cada upload é obrigado a ter uma imagem e um user
    validates :user_id, presence: true
    validates :image, presence: true
    validates :caption, length: { minimum: 2, maximum: 300 }
    
    scope :of_followed_users, -> (following_users) { where user_id: following_users }
    
    has_attached_file :image, styles: { :medium => "640x" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :like]
    before_action :owned_post, only: [:edit, :update, :destroy]
    
    def index
        if user_signed_in? && current_user.AdminPermissions
            flash[:success] = "Backoffice"
            @users = User.all
            respond_to do |format|
              format.html # index.html.erb
              format.json { render :json => @users }
            end
        else
            if user_signed_in?
                @posts = Post.of_followed_users(current_user.following).order("created_at DESC").page(params[:page]).per(5)
            else
                @posts = Post.all.order('created_at DESC').page(params[:page]).per(5)
            end
        end
    end
    
    def new
        @post = current_user.posts.new
    end
    
    def create
        @post = current_user.posts.create(post_params)
        if @post.save
            if current_user.posts.count == 1
                Follow.create(follower_id: current_user.id, following_id: current_user.id)
            end
            flash[:success] = "Imagem foi carregada com sucesso"    
            redirect_to root_path
        else
            flash.now[:error] = "Carregamento da imagem falhou"
            render :new
        end
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        if @post.update(post_params)
            redirect_to post_path(@post)
            flash[:success] = "Atualização com sucesso"
        else
            flash.now[:error] = "Atualização falhou"
            render :edit
        end
    end
    
    def browse
        @posts = Post.all.order('created_at DESC').page(params[:page]).per(5)
    end
    
    def destroy
        @postuser = @post.user.user_name
        if @post.destroy
            if current_user.AdminPermissions
                redirect_to :back
            else
                redirect_to profile_path(@postuser)
            end
            flash[:success] = 'Publicação apagada'
        end
    end
    
    def like
        if @post.liked_by current_user
            respond_to do |format|
                format.html { redirect_to :back }
                format.js
            end
        end
    end
    
    private
    
    def find_post
        @post = Post.find(params[:id])
    end
    
    def post_params
        params.require(:post).permit(:image, :caption)
    end
    
    def owned_post
        unless current_user == @post.user || current_user.AdminPermissions
            redirect_to root_path
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def display_likes(post)
        votes = post.votes_for.up.by_type(User) # numero de likes
        return list_likers(votes) if votes.size <= 5
        count_likers(votes)
    end
    
    def liked_post(post)
        if !user_signed_in?
            return 'glyphicon-heart-empty'
        else
            return 'glyphicon-heart' if current_user.voted_for? post
                'glyphicon-heart-empty'
        end
    end
    
    private    
    
    def list_likers(votes)
        user_names = []
        unless votes.blank?
            votes.voters.each do |voter|
                #por cada utilizador que gostou do post
                user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
            end
            #apresentar o array no html
            user_names.to_sentence.html_safe + likes_plural(votes)
        end
    end
    
    def count_likers(votes)
        vote_count = votes.size
        vote_count.to_s + 'gostos.'
    end

    def likes_plural(votes)
        return 'gostam disto.' if votes.count > 1 
        'gosta disto.'
    end
end

app/views/posts/_form.html.haml
.form-wrapper
    .post
        .post-body
            .image-wrap
                = image_tag 'placeholder2.jpg', id: 'image-preview', class: 'img-responsive'
                = simple_form_for @post, html: { multipart: true } do |f|
                    .row
                        .col-md-12.text-center
                            = f.error_notification
                    .container-fluid
                        .form-group.text-center
                            %h4 Carregar fotografia:
                            = f.input :image, label: false, input_html: {onChange: 'loadFile(event)'}
                        .form-group.text-center
                            = f.input :caption, label: false, placeholder: 'Escreva uma descrição...'
                        .form-group.text-center
                            = f.button :submit, value: 'Publicar', class: 'btn-info btn-block'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
    = display_likes post

app/views/posts/_post.html.haml
.container{ style: 'margin-top: 15px;'}
    .row
        .posts-wrapper.col-md-8
            .post
                .post-head
                    .thumb-img
                        = link_to profile_avatar_select(post.user), profile_path(post.user.user_name)
                    .user-name{ style: 'position:absolute; margin-top: 10px; margin-left: 55px;' }
                        = link_to post.user.user_name, profile_path(post.user.user_name)
                    .time-ago{ style: 'margin-top: 10px;' }
                        = link_to (time_ago_in_words post.created_at), post_path(post)
                .image.center-block
                    = image_tag post.image.url(:medium), class:'img-responsive'
                .post-bottom
                    = render 'posts/likes', post: post
                    .caption
                        .caption-content
                            .user-name
                                = link_to post.user.user_name, profile_path(post.user.user_name)
                        = post.caption
                    .comments{id: "comments_#{post.id}"}
                        - if post.comments
                            = render post.comments, post: post
                - if user_signed_in?
                    .comment-like-form.row
                        .like-button.col-sm-1
                            = link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "like glyphicon #{liked_post post}", title: "Gostar"
                        .comment-form.col-sm-11
                            = form_for([post, post.comments.new], remote: true) do |f|
                                = f.text_field :content, placeholder: 'Escreve um comentário...', class: "comment_content", id: "comment_content_#{post.id}"
        .panel.panel-info.col-sm-5{:style => "margin-top: 27px"}
            .panel-heading 
                .panel-title Peças de Roupa
                - if user_signed_in?
                    - if post.user.id == current_user.id
                        .pull-right{:style => "margin-top: -20px;"}
                            = link_to post_path(post), title: "Editar" do
                                %i.glyphicon.glyphicon-pencil
            %ul.list-group
                %table.table#tablepop
                    %tr
                        %th Peça
                        %th Preço
                        %th Loja
                        %th
                    - if post.clothes           
                        - post.clothes.each do |clothe|
                            %tr
                                %td=clothe.clothe_name
                                %td=number_to_currency(clothe.price, :locale => :pt)
                                %td=clothe.store_name
                                %td
                                    - if user_signed_in?
                                        - if post.user.id == current_user.id
                                            .btn.btn-danger.btn-xs
                                                = link_to 'Remover', post_clothe_path(post,clothe), id: clothe.id ,class: "deleteLink", :style => "text-decoration:none; color: inherit;", :method => :delete, data: {remote: true}
                                        - else
                                            .btn.btn-success.btn-xs
                                                = link_to 'Comprar', clothe.store_link, :style => "text-decoration:none; color: inherit;"
        - if user_signed_in? && current_user.AdminPermissions
            = button_to "Apagar publicação", post, :class => 'btn btn-danger', method: :delete, data: { confirm: "Tem a certeza que quer apagar a publicação?" }

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/browse.html.haml
#posts
    = render 'posts'
        
#paginator.text-center
    = link_to_next_page @posts, 'CARREGAR MAIS', remote: true, id:'load_more'

app/views/posts/browse.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%=escape_javascript(link_to_next_page(@posts, 'CARREGAR MAIS', remote: true, id: 'load_more'))%>");

if (!$('#load_more').length) { 
    $('#paginator').remove(); 
}

app/views/posts/edit.html.haml
.text-center
    = image_tag @post.image.url(:medium)
    
= render 'form'

.text-center.edit-links
    = link_to "Apagar Imagem", post_path(@post), method: :delete, data: { confirm: "Nao é esta pagina!!!!!" }
    |
    = link_to "Voltar", post_path(@post)

app/views/posts/index.html.haml
- if user_signed_in? && current_user.AdminPermissions
    = render 'admin/backoffice'
- else
    #posts
        = render 'posts'
        - if user_signed_in?
            - if current_user.following.count == 0
                .h3.col-md-12.text-center Ainda não segues ninguem. Procura novas pessoas na página Explorar
                %br
    #paginator.text-center
        = link_to_next_page @posts, 'CARREGAR MAIS', remote: true, id:'load_more'

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%=escape_javascript(link_to_next_page(@posts, 'CARREGAR MAIS', remote: true, id: 'load_more'))%>");

if (!$('#load_more').length) { 
    $('#paginator').remove(); 
}

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial:'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render 'post', post: @post
        
- if user_signed_in? && @post.user.id == current_user.id
    .text-center
        = render 'clothes/new'
    .text-center.edit-links
        = link_to "Apagar publicação", post_path(@post), method: :delete, data: { confirm: "Tem a certeza que quer apagar a publicação?" }
        |
        = link_to "Voltar", root_path
- else
    .text-center.edit-links
        = link_to "Voltar", root_path